config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
                       sign_up: "", #To Stop Sign Up action
                     }

  root to: "orders#index"

  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :phone, :presence => { :message => "Only positive number without spaces are allowed!" },
                    :numericality => true,
                    :length => { :minimum => 10, :maximum => 15 }
  validates :amount, :presence => { :message => "Only positive number without spaces are allowed!" },
                     :numericality => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.all.includes(:user)
    @users = []
    @orders.each do |o|
      @users << [o.user.id, o.user.username]
    end
    @users = @users.uniq
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    if params[:email].present?
      user = User.find_by(email: params[:email])
      u = user.present? ? user : User.create(username: params[:name], email: params[:email], password: "p@ssw0rd")
      params[:user_id] = u.id
      if params[:user_id].present?
        @order = Order.new(params.require(:order).permit(:phone, :address, :delivery_date, :item_id, :payment_option, :amount, :order_status, :user_id))
        if @order.save
          redirect_to orders_path, :notice => "Order was successfully created."
        else
          redirect_to new_order_path, :alert => "Something went wrong! Please try again"
        end
      else
        redirect_to new_order_path, :alert => "Something went wrong! Please try again"
      end
    else
      redirect_to new_order_path, :alert => "Please fill email ID column"
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    is_status_change = (@order.order_status != params["status"])
    if @order.update(params.require(:order).permit(:phone, :address, :delivery_date, :item_id, :payment_option, :amount, :order_status))
      AlertsMailer.send_alert(User.find(@order.user_id), @order).deliver_now! if is_status_change
      redirect_to orders_path, :notice => "Order was successfully updated."
    else
      redirect_to edit_order_path(params[:id]), :alert => "Something went wrong! Please try again"
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to orders_path, :notice => "Order was successfully deleted."
    else
      redirect_to orders_path, :alert => "Something went wrong! Please try again"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<% if user_signed_in? %>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %> | Order System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= stylesheet_link_tag "print", :media => "print" %>
    <!-- This refers to app/javascript/stylesheets/application.scss-->
    <%= stylesheet_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <!-- Mainly scripts -->
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body class="fixed-nav fixed-nav-basic"> <!-- min sidemenu: mini-navbar-->
    <div id="wrapper">
      <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
          <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
              <div class="dropdown profile-element">
                <span>
                  <h2 style="font-size: 30px; margin-bottom: 20px; color: #e891f4">Order <span style="color: #b651a7; font-weight: 900">System</span></h2>
                </span>
                <!--<a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <span class="clear">
                      <span class="block m-t-xs">
                          <strong class="font-bold">Order System</strong> <b class="caret"></b>
                      </span>
                  </span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                </ul>-->
              </div>
              <div class="logo-element">
                <h2 style="font-size: 10px; margin-top: 0px; margin-bottom: 0px; color: #e891f4">Order <span style="color: #b651a7; font-weight: 900">System</span></h2>
              </div>
            </li>
            <li class="landing_link">
              <%= link_to orders_path do %>
                <i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span>
              <% end %>
            </li>
            <li class="active">
              <%= link_to orders_path do %>
                <i class="fa fa-shopping-bag"></i> <span class="nav-label">All Orders</span> 
              <% end %>
            </li>
            <% # <li class="active"> %>
              <% #= link_to new_order_path do %>
                <% # <i class="fa fa-plus-circle"></i> <span class="nav-label">Add Order</span> %>
              <% # end %>
            <% # </li> %>
            <% # <li class="active"> %>
              <% #= link_to edit_user_registration_path do %>
                <% # <i class="fa  fa-pencil-square"></i> <span class="nav-label">Change Password</span> %>
              <% # end %>
            <% # </li> %>
          </ul>
        </div>
      </nav>

      <div id="page-wrapper" class="gray-bg" style="min-height: 600px;">
        <div class="row border-bottom">
          <nav class="navbar navbar-fixed-top white-bg" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
              <% # <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " data-toggle="collapse" href="#sidebar"><i class="fa fa-bars"></i> </a> %>
            </div>
            <ul class="nav navbar-top-links navbar-right">
              <li style="padding: 20px 10px">
                <span class="m-r-sm text-muted"><strong>Order</strong> System.</span>
              </li>
              <li class="pull-right">
                <%= link_to destroy_user_session_path, :method => "delete" do %>
                    <i class="fa fa-sign-out"></i> Log out
                <% end %>
              </li>
            </ul>
          </nav>
        </div>

        <div class="wrapper wrapper-content">

          <% if notice %>
              <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Notice!</strong> <%= notice %>
              </div>
          <% end %>

          <% if alert %>
              <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Alert!</strong> <%= alert %>
              </div>
          <% end %>

          <%= yield %>

        </div>

        <div class="footer">
          <div class="pull-right">
             BY <strong><span style="color: #e891f4">Order</span><span style="color:#b651a7"> System</span></strong>
          </div>
          <div>
            <strong>Copyright</strong> Order System &copy; <%= Time.now.year %>
          </div>
        </div>
      </div>
    </div>

    <!-- Custom and plugin javascript -->
    <script type="text/javascript">
      $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
      });
    </script>

    <% if notice %>
      <script>
        $(document).ready(function() {
          setTimeout(function() {
            toastr.options = {
              closeButton: true,
              progressBar: true,
              showMethod: 'slideDown',
              timeOut: 4000
            };
            toastr.success('<%= notice %>', 'Notice');
          }, 1300);
        });
      </script>
    <% end %>

    <script>
      $.fn.dataTable.ext.search.push(
        function( settings, data, dataIndex ) {
            var order_status =  $('#order_status').val().trim();
            var user =  $('#user').val().trim();
            var order_status_val = data[7].trim();
            var user_val =  data[0].trim();
            if (order_status == "All" && user == "All" ){
              return true
            }
            if ( 
              order_status == order_status_val && user == "All" ||
              order_status == "All" && user == user_val ||
              order_status == order_status_val && user == user_val
             ){
                return true;
            }
            return false;
        }
      );
      $(document).ready(function(){
        var table = $('.dataTables-example').DataTable();
         // Event listener to the two range filtering inputs to redraw on input
        $('#order_status, #user').change( function() {
            table.draw();
        });
      })
    </script>
         
  </body>
</html>

<% else %>

<!DOCTYPE html>
  <html>

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title>Login | Order System</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
      <%= stylesheet_link_tag "print", :media => "print" %>
  
      <!-- Mainly scripts -->
      <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    </head>

    <body class="gray-bg">
    <div class="middle-box text-center loginscreen animated fadeInDown">
      <div>

        <%= yield %>

      </div>
    </div>

    <div class="footer">
      <div class="pull-right">
        BY <strong><span style="color: #e891f4">Order</span><span style="color:#b651a7"> System</span></strong>
      </div>
      <div>
        <strong>Copyright</strong> Order System &copy; <%= Time.now.year %>
      </div>
    </div>

    </body>

  </html>

<% end %>

app/views/orders/edit.html.erb
<% content_for :title, "Edit Order" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Edit Order </h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">
      <%= form_for @order do |f| %>
          <div class="col-sm-6 b-r">
            <h3 class="m-t-none m-b">Customer Info</h3>
            <div class="form-group">
              <label>Phone</label>
              <%= f.text_field :phone, :placeholder => "Enter phone number", :class => "form-control", :required => "" %>
            </div>
            <div class="form-group">
              <label>Address</label>
              <%= f.text_area :address, :placeholder => "Enter full address", :class => "form-control", :rows => "3", :required => "" %>
            </div>
          </div>
          <div class="col-sm-6"><h3 class="m-t-none m-b">Order Info</h3>
            <div class="form-group">
              <label>Delivery Date</label>
              <%= f.date_field :delivery_date, :class => "form-control", :required => "" %>
            </div>
            <div class="form-group">
              <label>Item ID</label>
              <%= f.text_area :item_id, :placeholder => "Enter item id", :class => "form-control", :rows => "3", :required => "" %>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Select Payment Option</label>
                  <%= f.select :payment_option, options_for_select(["Postpay", "Prepay (Full)", "Prepay (Half)"], :selected => f.object.payment_option), {}, { :class => "form-control m-b", :required => "" } %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Amount</label>
                  <%= f.text_field :amount, :placeholder => "Enter total amount", :class => "form-control", :required => "" %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="row">
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                <label class="col-sm-2">Status</label>
                <div class="col-sm-10">
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Confirmed", :class => "icheckbox_square-green" %> Confirmed </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Ready", :class => "icheckbox_square-green" %> Ready </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Send", :class => "icheckbox_square-green" %> Send </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Delivered", :class => "icheckbox_square-green" %> Delivered </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Returned", :class => "icheckbox_square-green" %> Returned </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Cancelled", :class => "icheckbox_square-green" %> Cancelled </label>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class => "btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<% content_for :title, "All Orders" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>All Orders Data</h5>
        <div class="ibox-tools">
          <div class="col-sm-6 col-md-6">
          <tr>
            <div class="col-sm-12 col-md-4" style="align: right"><td>Order status:</td></div>
            <div class="col-sm-12 col-md-8" style="margin-top:-8px">
              <td class="col-sm-6 col-md-3">
                <select class="custom-select custom-select-sm form-control form-control-sm" aria-label="Disabled select example" id="order_status">
                  <option value="All" selected>All</option>
                  <option value="Confirmed">Confirmed</option>
                  <option value="Ready">Ready</option>
                  <option value="Send">Send</option>
                  <option value="Delivered">Delivered</option>
                  <option value="Returned">Returned</option>
                  <option value="Cancelled">Cancelled</option>
                </select>
              </td>
            </div>  
          </tr>
          </div>
          <div class= "col-sm-6 col-md-3">
           <tr>
           <div class="col-sm-12 col-md-4" style="align: right">
            <td>Users:</td>
            </div>
            <div class="col-sm-12 col-md-8" style="margin-top:-8px">
            <td>
              <select class="custom-select custom-select-sm form-control form-control-sm" aria-label="Disabled select example" id="user">
                <option value="All" selected>All</option>
                <% @users.each do |user| %>
                  <option value="<%= user[1] %>"><%= user[1] %></option>
                <% end %>
              </select>
            </td>
            </div>
          </tr> 
          </div>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Item</th>
                <th>Payment Option</th>
                <th>Amount</th>
                <th>Status</th>
                <th width="101px">Buttons</th>
              </tr>
            </thead>

            <tbody>

            <% @orders.each do |order| %>

              <tr class="">
                <td><%= order.user.username %></td>
                <td><%= order.phone %></td>
                <td><%= order.address %></td>
                <td><%= order.delivery_date %></td>
                <td><%= order.item_id %></td>
                <td><%= order.payment_option %></td>
                <td><%= order.amount %></td>
                <td><span class="badge badge-primary"> <%= order.order_status %></span></td>
                <td>
                  <%= link_to order_path(order.id), :class => "btn btn-white btn-bitbucket", method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_order_path(order.id), :class => "btn btn-white btn-bitbucket" do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>

            <% end %>

            </tbody>

            <tfoot>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Item</th>
                <th>Payment Option</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Buttons</th>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<% content_for :title, "Add Order" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Add Order <small>Please </small></h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">
      <%= form_for @order do |f| %>
          <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Customer Info</h3>
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, :placeholder => "Enter full name", :class => "form-control", :required => "" %>
            </div>
            <div class="form-group">
              <label>Phone</label>
              <%= f.text_field :phone, :placeholder => "Enter phone number", :class => "form-control", :required => "" %>
            </div>
            <div class="form-group">
              <label>Address</label>
              <%= f.text_area :address, :placeholder => "Enter full address", :class => "form-control", :rows => "3", :required => "" %>
            </div>
          </div>
          <div class="col-sm-6"><h3 class="m-t-none m-b">Order Info</h3>
            <div class="form-group">
              <label>Delivery Date</label>
              <%= f.date_field :delivery_date, :class => "form-control", :required => "" %>
            </div>
            <div class="form-group">
              <label>Item ID</label>
              <%= f.text_area :item_id, :placeholder => "Enter item id", :class => "form-control", :rows => "3", :required => "" %>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Select Payment Option</label>
                  <%= f.select :payment_option, options_for_select(["Postpay", "Prepay (Full)", "Prepay (Half)"]), {}, { :class => "form-control m-b", :required => "" } %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Amount</label>
                  <%= f.text_field :amount, :placeholder => "Enter total amount", :type => "number", :class => "form-control", :required => "" %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="row">
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                <label class="col-sm-2">Status</label>
                <div class="col-sm-10">
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Confirmed", :class => "icheckbox_square-green" %> Confirmed </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Ready", :class => "icheckbox_square-green" %> Ready </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Send", :class => "icheckbox_square-green" %> Send </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Delivered", :class => "icheckbox_square-green" %> Delivered </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Returned", :class => "icheckbox_square-green" %> Returned </label>
                  <label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, "Cancelled", :class => "icheckbox_square-green" %> Cancelled </label>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class => "btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<% content_for :title, "Print Order" %>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-8">
    <h2>Invoice</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to "Home", orders_path %>
      </li>
      <li class="active">
        <strong>Invoice</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-4">
    <div class="title-action">
      <button href="#" onclick="print_invoice()" class="btn btn-primary"><i class="fa fa-print"></i> Print Invoice </button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">

    <div class="wrapper wrapper-content animated fadeInRight" id="print">
      <div class="ibox-content p-xl">

        <div class="invoice_head">
          <div class="row">
            <div class="col-xs-10">
              <h2 style="font-size: 30px; margin-bottom: 20px; color: #e891f4">Order <span style="color: #b651a7; font-weight: 900">System</span></h2>
              <p>
                Company address, Road: xx<br>
                Dhaka 12xx
              </p>
            </div>
          </div>
        </div>
        <hr>
        <h4 class="text-center">INVOICE</h4>
        <div class="row">
          <div class="col-xs-6">
            <h5>To:</h5>
            <address>
              <strong><%= @order.name %></strong><br>
              <%= @order.address %><br>
              <b>Phone :</b> <%= @order.phone %>
            </address>
          </div>

          <div class="col-xs-6 text-right">
            <h4>Invoice No.</h4>
            <h4 class="text-navy">INV-000-<%= @order.id %></h4>
            <p>
              <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br />
              <span><strong>Due Date:</strong> <%= @order.delivery_date %></span>
            </p>
          </div>
        </div>

        <div class="table-responsive m-t">
          <table class="table invoice-table">
            <thead>
            <tr>
              <th>Item List</th>
              <th>Price (Taka)</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>
                <div><%= @order.item_id %></div>
              </td>
              <td>Tk <%= @order.amount %></td>
            </tr>
            </tbody>
          </table>
        </div><!-- /table-responsive -->

        <hr style="margin-top: 0px;">

        <div class="row">
          <div class="col-xs-6">
            <div class="well m-t">
              <strong>Comments</strong>
              It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
            </div>
          </div>
          <div class="col-xs-6">
            <table class="table invoice-total">
              <tbody>
              <tr>
                <td><strong>Sub Total :</strong></td>
                <td>Tk <%= @order.amount %></td>
              </tr>
              <tr>
                <td><strong>TAX :</strong></td>
                <td>Tk 0</td>
              </tr>
              <tr>
                <td><strong>TOTAL :</strong></td>
                <td style="border: 1px solid #DDDDDD;">Tk <%= @order.amount %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <p>
              Recvied By : __________________
            </p>
          </div>
          <div class="col-xs-6 text-right">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function print_invoice() {
    window.print();
  }
</script>